@startuml

skinparam ClassAttributeIconSize 0

abstract GeometricObject {
    -color: String
    -filled: boolean
    -dateCreated: java.util.Date

    #GeometricObject()
    #GeometricObject(color: string, filled: boolean)
    +getColor(): String 
    +setColor(color: String): void
    +isFIlled(): boolean
    +setFilled(filled: boolean): void
    +getDateCreated(): java.util.Date
    +toString(): String 
    {abstract} +getArea(): double
    {abstract} +getPerimeter(): double

}

class Triangle extends GeometricObject {
    -sideOne: double
    -sideTwo: double
    -sideThree: double

    +Triangle()
    +Triangle(sideOne: double, sideTwo: double,\n\tsideThree: double)
    +Triangle(sideOne: double, sideTwo: double, \n\tsideThree: double, color: string,\n\tfilled: boolean)
    +getSideOne(): double
    +getSideTwo(): double
    +getSideThree(): double
    +setSideOne(sideOne: double)
    +setSideTwo(sideTwo: double)
    +setSideThree(sideThree: double)
}




@enduml 